import logging
from app.services.gemini_service import gemini_service
from app.services.whatsapp_service import whatsapp_service
from app.models.sql_models import User, BusinessProfile
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

class WhatsAppOrchestratorAgent:
    """
    Acts as the 'brain' for the conversational interface.
    Receives incoming WhatsApp text, parses intent, and triggers actions.
    """
    
    async def process_incoming_message(self, phone_number: str, message_text: str, db: Session):
        # 1. Find user by phone number
        user = db.query(User).filter(User.phone == phone_number).first()
        
        if not user:
            # Welcome new unspecified user
            await whatsapp_service.send_message(
                phone_number,
                "Welcome to SellSenseai! I don't recognize this number. Please log in to the dashboard and add your phone number to your profile to enable autonomous commands via WhatsApp."
            )
            return

        business = db.query(BusinessProfile).filter(BusinessProfile.user_id == user.id).first()
        business_name = business.business_name if business else "your business"

        # 2. Parse Intent using Gemini
        prompt = f"""You are the orchestrator AI for {business_name}. 
        A user has sent you a WhatsApp message. Parse their intent and extract parameters.
        
        User Message: "{message_text}"
        
        Return JSON ONLY:
        {{
            "intent": "create_campaign" | "status_update" | "generic_chat" | "unknown",
            "campaign_topic": "Extracted topic or null",
            "campaign_budget": "Extracted budget or null",
            "response_text": "A friendly confirmation message to send immediately back to the user via WhatsApp (e.g. 'Got it! I am crafting a campaign for X right now...')"
        }}"""

        parsed_data = gemini_service.generate_json(prompt, max_tokens=800)
        
        if not parsed_data:
            await whatsapp_service.send_message(
                phone_number,
                "I'm sorry, my AI brain had a slight glitch understanding that. Could you rephrase it?"
            )
            return

        # 3. Send immediate response to user
        response_text = parsed_data.get("response_text", "Understood. Let me process that for you.")
        await whatsapp_service.send_message(phone_number, response_text)

        # 4. Handle specific intents
        intent = parsed_data.get("intent")
        
        if intent == "create_campaign":
            # Here we would trigger the full Analyst -> Strategy -> Content pipeline
            # Typically this would be pushed to a background task cue like Celery. 
            # For this MVP simulation, we simulate the delay and then send a success message.
            import asyncio
            asyncio.create_task(self._simulate_campaign_creation(phone_number, parsed_data))

    async def _simulate_campaign_creation(self, phone_number: str, parsed_data: dict):
        import asyncio
        await asyncio.sleep(5)  # Simulate API processing time for Strategy and Content Bots
        
        topic = parsed_data.get("campaign_topic", "your topic")
        success_msg = f"🎉 Great news! Your campaign for '{topic}' has been fully generated by the AI Strategy & Content bots. Check your dashboard to approve the final videos and posts!"
        
        await whatsapp_service.send_message(phone_number, success_msg)

whatsapp_agent = WhatsAppOrchestratorAgent()
